apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-server444444
  namespace: ml-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-server
  template:
    metadata:
      labels:
        app: model-server
    spec:
      containers:
      - name: ml-model-container
        image: nginx:latest
        ports:
        - containerPort: 80
